### ISSUE TITLE
can't use the services

### ISSUE THREAD

**Issue by uriahf** [ColumbusCollaboratory/cognizer#10]
Hello everyone, I was trying to  use the text to speech feature but I'm not sure what should i put in the SPEECH_TO_TEXT_USERNAME_PASSWORD object. In the YOUR_API_KEY object I used to put my passward as a string.

**Comment by petegordon** [comment]
When using SPEECH_TO_TEXT_USERNAME_PASSWORD it's a little tricky.  It needs to be the username followed by a colon then followed by the password as in the documentation here...

SERVICE_USERNAME_PASSWORD = "username:password"

It is using the same CURL/HTTP syntax as in the IBM documentation here... https://www.ibm.com/watson/developercloud/doc/speech-to-text/http.html

**Comment by Uriahf** [comment]
I tried it that way, it still didn't work out!

By username you mean this odd code i'm getting in the "Service credentials"
tab?

it should be written as a string right?

let's say i'm getting something like this ( i just made those numbers up):

  "username": "1234aa1234",
  "password": "5555bb5555"

so the SPEECH_TO_TEXT_USERNAME_PASSWORD should be

"1234aa1234:5555bb5555"

right?

thanks for your time and effort :)

**Comment by petegordon** [comment]
Hi Uriahf!  I think we resolved this on the phone a couple months ago.  I'm going to close it.  If you have any issues; post a comment here.  Hope you are doing well!  And, getting some good use out of CognizeR.
