### ISSUE TITLE
Alchemy Language

### ISSUE THREAD

**Issue by rexhu100** [ColumbusCollaboratory/cognizer#11]
The Alchemy Language API is no longer available in Bluemix. Its functionalities are primarily replaced by Natural Language Understanding. Any plan to update your package to work with the new API?

**Comment by ricardo-rei** [comment]
I'm trying to use a few of the Alchemy Language API functions.
If I understood ir right, those functions are no longe working as these APIs have been replaced for some other IBM services, right?
this last comment is from july 10 (more then 2 months ago). but still valid. 
any idea when will thew cognizeR with Natural Language Understanding and other IBM watson services? (like Discovery)

**Comment by petegordon** [comment]
IBM just renamed the Alchemy services to Natural Language Understanding.  I just ran through the install, and ran sentiment (with my own API_KEY) and it worked fine.

![image](https://user-images.githubusercontent.com/1993032/30745516-8477ec88-9f74-11e7-8ad2-8278a3bcf9da.png)

**Comment by petegordon** [comment]
Just discovered that you may not be able to get an API for Alchemy.  If you don't have a Alchemy API already, I am sorry but you wont be able to use the package until it is updated to Natural Language Understanding.  If you do have a Alchemy API, it will be good until March 7, 2018.

[IBM Migration Steps](https://console.bluemix.net/docs/services/natural-language-understanding/migrating.html#migrating-from-alchemylanguage)

**Comment by ricardo-rei** [comment]
exactly my problem. I can have credentials for the available today watson services (which are mainly with a username and password format). I don't have de credentials needed for the Alchemy cognizeR functions (API_KEY,...).
any idea when will the package be updated?
thanks

**Comment by petegordon** [comment]
Understood.  Sorry, don't have a time for update yet.  Other than hopefully before March 2018.
