### ISSUE TITLE
Unable to load package

### ISSUE THREAD

**Issue by bdwyer2** [ColumbusCollaboratory/cognizer#2]
I get the following error when I call the package:

> library(cognizer)
> Error : object ‘multi_add’ is not exported by 'namespace:curl'
> Error: package or namespace load failed for ‘cognizer’`

R 3.3.1
curl 1.1.9000
cognizer 0.0.1
Linux Mint 18 (x86_64-pc-linux-gnu)

**Comment by lozass** [comment]
I get the following error upon loading the package:

> library(cognizer)
Error : object ‘multi_add’ is not exported by 'namespace:curl'
Error: package or namespace load failed for ‘cognizer’

> version
               _                           
platform       x86_64-apple-darwin14.5.0   
arch           x86_64                      
os             darwin14.5.0                
system         x86_64, darwin14.5.0        
status                                     
major          3                           
minor          3.1                         
year           2016                        
month          06                          
day            21                          
svn rev        70800                       
language       R                           
version.string R version 3.3.1 (2016-06-21)
nickname       Bug in Your Hair    

 curl_1.1.9000 
devtools_1.12.0

**Comment by slavaua87** [comment]
At the moment multi_add is part of the development version of curl, so you need to install the github version. Try devtools::install_github("jeroenooms/curl") and then loading cognizer.
