### ISSUE TITLE
text_personality error

### ISSUE THREAD

**Issue by LizBae** [ColumbusCollaboratory/cognizer#4]
I allocate my username and password to 'MY_useranme' and 'MY_password'.
And then running below.
text <- paste(replicate(1000, rmsfact::rmsfact()), collapse = ' ')
text_personality(text, 'MY_username:MY_password')

Error: lexical error: invalid char in json text.
                                       <HTML><HEAD><meta content="text
                     (right here) ------^

**Comment by slavaua87** [comment]
Works on my setup. This error arises when username:password pair is not correct. Did you register personality service separately?

**Comment by petegordon** [comment]
Hi.  Here is the place where the specific Bluemix service username and password (also called service credentials) are shown how to create and retrieve on Bluemix. [https://www.ibm.com/watson/developercloud/doc/getting_started/gs-credentials.shtml]( https://www.ibm.com/watson/developercloud/doc/getting_started/gs-credentials.shtml)  

Is that the Username and Password you are using?  The service credential username is a very long string looks like a UUID.

**Comment by LizBae** [comment]
Yes. Yes.
I registered a personality insights service on BlueMix and got credentials. It's very long long username and password like tAU~~~~.

**Comment by LizBae** [comment]
I solved!
This error is for 'MY_username' and 'MY_password' variables, I guess.
Not allocating, just paste username : password!!! ^^;;;;;

**Comment by petegordon** [comment]
Great!  Let us know if you have other issues and as you build things.  Best!
