### ISSUE TITLE
Authentication snag

### ISSUE THREAD

**Issue by ideamonger** [ColumbusCollaboratory/cognizer#7]
I am trying to access sentiment analysis through the alchemy service. I have the api key. I enter 

text <- c("Columbus, Ohio is Awesome!", "Looking forward to UseR2017 in Brussels!")
result <- text_sentiment(text, Yaa6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
str(result)

and I get

> text <- c("Columbus, Ohio is Awesome!", "Looking forward to UseR2017 in Brussels!")
> result <- text_sentiment(text, Yaa6xxxxxxxxxxxxxxxxxxxx)
Error in paste(c("apikey", "outputMode", "showSourceText"), c(api_key,  : 
  object 'Yaa6xxxxxxxxxxxxxxxxxxxxxxxxxxxxx' not found
> str(result)
Error in str(result) : object 'result' not found

Is they key not recognized or is the syntax wrong?

**Comment by synikitin** [comment]
Hey,

It looks like your key is a name of a vector and not a string, that's why you are getting "object 'Yaa6xxxxxxxxxxxxxxxxxxxxxxxxxxxxx' not found".

So pass "Yaa6xxxxxxxxxxxxxxxxxxxxxxxxxxxxx" to the function.

**Comment by ideamonger** [comment]
got it...
